### Main repository URL pointing to this repo
main_repo_url: https://github.com/kubealex/rhel-leapp-aap.git

### URL and creds for AAP2 Controller
aap2_controller_url: https://aap.rh-lab.labs:8443
aap2_controller_username: admin
aap2_controller_password: redhat

aap2_organization: "Default"

### Credentials for hosts
inventory_servers_username: sysadmin
inventory_servers_password: redhat
