### Main repository URL pointing to this repo
main_repo_url: https://github.com/kubealex/rhel-leapp-aap.git

### URL and creds for AAP2 Controller
aap2_controller_url: https://aap.rh-lab.labs:8443
aap2_controller_username: admin
aap2_controller_password: redhat

aap2_organization: "Default"

### Credentials for hosts
inventory_servers_username: sysadmin
inventory_servers_password: redhat

### DO NOT CHANGE VARIABLES BELOW THIS LINE ###

servers_survey_spec:
  description: "RHEL Upgrade survey"
  name: "RHEL Upgrade survey"
  spec:
    - question_name: "Server name/Group Name"
      question_description: "Name of the server or server group as present in inventory"
      required: true
      type: "text"
      default: "rhel_servers"
      index: 0
      variable: "target_hosts"

leapp_survey_spec:
  description: "RHEL Upgrade survey"
  name: "RHEL Upgrade survey"
  spec:
    - question_name: "Server name/Group Name"
      question_description: "Name of the server or server group as present in inventory"
      required: true
      type: "text"
      default: "rhel_servers"
      index: 0
      variable: "target_hosts"
    - question_name: "Content source used for the upgrade"
      question_description: "What source should be used when configuring leapp"
      required: true
      type: "multiplechoice"
      choices:
        - "satellite"
        - "cdn"
        - "rhui"
      default: "cdn"
      index: 1
      variable: "upgrade_source"
    - question_name: "Satellite Organization"
      question_description: "Name of the Satellite organization to use"
      required: false
      type: "text"
      default: ""
      index: 2
      variable: "upgrade_satellite_organization"
    - question_name: "Satellite Activation Key"
      question_description: "Name of the Satellite activation key to use"
      required: false
      type: "text"
      default: ""
      index: 3
      variable: "upgrade_satellite_activation_key"

controller_credentials:
  - name: "RHEL AAP Upgrade - Linux Credentials"
    credential_type: "Machine"
    organization: "{{ aap2_organization }}"
    inputs:
      username: "{{ inventory_servers_username }}"
      password: "{{ inventory_servers_password }}"

controller_projects:
  - name: "RHEL AAP Upgrade"
    scm_url: "{{ main_repo_url }}"
    scm_type: "git"
    scm_update_on_launch: false
    organization: "{{ aap2_organization }}"
    default_environment: "Minimal execution environment"
    update_project: true
    wait: true
    timeout: 60

  # ------------------------------------
  # ------------------------------------
controller_inventories:
  - name: RHEL AAP Upgrade - SCM Inventory
    organization: "{{ aap2_organization }}"
  # ------------------------------------
  # ------------------------------------

controller_inventory_sources:
  - name: RHEL AAP Upgrade - SCM Inventory Source
    inventory: RHEL AAP Upgrade - SCM Inventory
    source: scm
    source_project: "RHEL AAP Upgrade"
    source_path: inventory
    organization: "{{ aap2_organization }}"

  # ------------------------------------
  # ------------------------------------

controller_templates:
  - name: "[RHEL AAP Upgrade] Run pre-flight checks"
    organization: "{{ aap2_organization }}"
    playbook: playbooks/leapp-pre-flight-checks.yml
    credentials:
      - RHEL AAP Upgrade - Linux Credentials
    inventory: RHEL AAP Upgrade - SCM Inventory
    project: RHEL AAP Upgrade
    survey_enabled: true
    servers_survey_spec: "{{ servers_survey_spec }}"
    # ------------------------------------
  - name: "[RHEL AAP Upgrade] Configure LVM Snapshots for servers"
    organization: "{{ aap2_organization }}"
    playbook: playbooks/leapp-configure-lvm-snapshot.yml
    credentials:
      - RHEL AAP Upgrade - Linux Credentials
    inventory: RHEL AAP Upgrade - SCM Inventory
    project: RHEL AAP Upgrade
    survey_enabled: true
    servers_survey_spec: "{{ servers_survey_spec }}"
    # ------------------------------------
  - name: "[RHEL AAP Upgrade] Run LEAPP Analysis"
    organization: "{{ aap2_organization }}"
    playbook: playbooks/leapp-analysis.yml
    credentials:
      - RHEL AAP Upgrade - Linux Credentials
    inventory: RHEL AAP Upgrade - SCM Inventory
    project: RHEL AAP Upgrade
    survey_enabled: true
    servers_survey_spec: "{{ leapp_survey_spec }}"
    # ------------------------------------
  - name: "[RHEL AAP Upgrade] Run LEAPP Upgrade"
    organization: "{{ aap2_organization }}"
    playbook: playbooks/leapp-upgrade.yml
    credentials:
      - RHEL AAP Upgrade - Linux Credentials
    inventory: RHEL AAP Upgrade - SCM Inventory
    project: RHEL AAP Upgrade
    survey_enabled: true
    servers_survey_spec: "{{ leapp_survey_spec }}"
    # ------------------------------------
  - name: "[RHEL AAP Upgrade] Rollback system upgrade"
    organization: "{{ aap2_organization }}"
    playbook: playbooks/leapp-rollback.yml
    credentials:
      - RHEL AAP Upgrade - Linux Credentials
    inventory: RHEL AAP Upgrade - SCM Inventory
    project: RHEL AAP Upgrade
    survey_enabled: true
    servers_survey_spec: "{{ servers_survey_spec }}"
    # ------------------------------------
  - name: "[RHEL AAP Upgrade] Remove LVM Snapshots"
    organization: "{{ aap2_organization }}"
    playbook: playbooks/leapp-remove-snapshot.yml
    credentials:
      - RHEL AAP Upgrade - Linux Credentials
    inventory: RHEL AAP Upgrade - SCM Inventory
    project: RHEL AAP Upgrade
    survey_enabled: true
    servers_survey_spec: "{{ servers_survey_spec }}"
    # ------------------------------------
  - name: "[RHEL AAP Upgrade] Remediate inhibitors"
    organization: "{{ aap2_organization }}"
    playbook: playbooks/leapp-remediate.yml
    credentials:
      - RHEL AAP Upgrade - Linux Credentials
    inventory: RHEL AAP Upgrade - SCM Inventory
    project: RHEL AAP Upgrade
    survey_enabled: true
    servers_survey_spec: "{{ servers_survey_spec }}"

controller_workflows:
  - name: "[RHEL AAP Upgrade] Prepare systems for upgrade"
    organization: "{{ aap2_organization }}"
    survey_enabled: true
    servers_survey_spec: "{{ leapp_survey_spec }}"
    simplified_workflow_nodes:
      - identifier: leapp-pre-flight
        nodes_on_success:
          - leapp-configure-lvm-snapshot
        unified_job_template: "[RHEL AAP Upgrade] Run pre-flight checks"
      - identifier: leapp-configure-lvm-snapshot
        nodes_on_success:
          - leapp-analysis
        unified_job_template: "[RHEL AAP Upgrade] Configure LVM Snapshots for servers"
      - identifier: leapp-analysis
        approval: false
        unified_job_template: "[RHEL AAP Upgrade] Run LEAPP Analysis"

  - name: "[RHEL AAP Upgrade] Remediate inhibitors and re-run analysis"
    organization: "{{ aap2_organization }}"
    survey_enabled: true
    servers_survey_spec: "{{ leapp_survey_spec }}"
    simplified_workflow_nodes:
      - identifier: leapp-remediate-inhibitors
        nodes_on_success:
          - leapp-analysis
        unified_job_template: "[RHEL AAP Upgrade] Remediate inhibitors"
      - identifier: leapp-analysis
        unified_job_template: "[RHEL AAP Upgrade] Run LEAPP Analysis"

  - name: "[RHEL AAP Upgrade] Perform rollback on systems"
    organization: "{{ aap2_organization }}"
    survey_enabled: true
    servers_survey_spec: "{{ leapp_survey_spec }}"
    simplified_workflow_nodes:
      - identifier: leapp-rollback
        nodes_on_success:
          - leapp-remove-lvm-snapshot
        unified_job_template: "[RHEL AAP Upgrade] Rollback system upgrade"
      - identifier: leapp-remove-lvm-snapshot
        unified_job_template: "[RHEL AAP Upgrade] Remove LVM Snapshots"
