---
- name: Playbook for configuring AAP2 Controller resources
  hosts: localhost
  vars_files:
    - internal-vars.yml
    - config-vars.yml
  vars:
    aap_hostname: "{{ aap2_controller_url }}"
    aap_username: "{{ aap2_controller_username }}"
    aap_password: "{{ aap2_controller_password }}"
    aap_validate_certs: false
    aap_configuration_async_retries: 60
  roles:
    - role: infra.aap_configuration.dispatch
