### Main repository URL pointing to this repo
main_repo_url: https://github.com/kubealex/rhel-leapp-aap.git

### URL and creds for AAP2 Controller
aap2_controller_url: https://aap.rh-lab.labs:8443
aap2_controller_username: admin
aap2_controller_password: redhat

### Credentials for hosts
inventory_servers_username: sysadmin
inventory_servers_password: redhat


aap2_galaxy_credentials:
  - name: RHEL AAP Upgrade - Galaxy Credentials
    galaxy_url: "{{ automation_hub_url }}"
    galaxy_auth_url: "{{ automation_hub_auth_url }}"
    galaxy_token: "{{ automation_hub_token }}"

aap2_projects:
  - name: "RHEL AAP Upgrade"
    scm_url: "{{ main_repo_url }}"
    scm_branch: "main"
    default_ee: "Minimal execution environment"
    force_update: false
  # ------------------------------------
  # ------------------------------------

aap2_machine_credentials:
  - name: "RHEL AAP Upgrade - Linux Credentials"
    username: "{{ inventory_servers_username }}"
    password: "{{ inventory_servers_password }}"
  # ------------------------------------
  # ------------------------------------

aap2_inventories:
  - aap2_inventory_name: RHEL AAP Upgrade - SCM Inventory
  # ------------------------------------
  # ------------------------------------

aap2_inventory_sources:
  - aap2_inventory_source_name: RHEL AAP Upgrade - SCM Inventory Source
    aap2_inventory_source_inventory: RHEL AAP Upgrade - SCM Inventory
    aap2_inventory_source_type: scm
    aap2_inventory_source_project: "RHEL AAP Upgrade"
    aap2_inventory_source_path: inventory
  # ------------------------------------
  # ------------------------------------

aap2_templates:
  - aap2_template_name: "[RHEL AAP Upgrade] Run pre-flight checks"
    aap2_template_playbook: playbooks/leapp-pre-flight-checks.yml
    aap2_template_credentials:
      - RHEL AAP Upgrade - Linux Credentials
    aap2_template_inventory: RHEL AAP Upgrade - SCM Inventory
    aap2_template_project: RHEL AAP Upgrade
    # ------------------------------------
  - aap2_template_name: "[RHEL AAP Upgrade] Configure LVM Snapshots for servers"
    aap2_template_playbook: playbooks/leapp-configure-lvm-snapshot.yml
    aap2_template_credentials:
      - RHEL AAP Upgrade - Linux Credentials
    aap2_template_inventory: RHEL AAP Upgrade - SCM Inventory
    aap2_template_project: RHEL AAP Upgrade
    # ------------------------------------
  - aap2_template_name: "[RHEL AAP Upgrade] Run LEAPP Analysis"
    aap2_template_playbook: playbooks/leapp-analysis.yml
    aap2_template_credentials:
      - RHEL AAP Upgrade - Linux Credentials
    aap2_template_inventory: RHEL AAP Upgrade - SCM Inventory
    aap2_template_project: RHEL AAP Upgrade
    # ------------------------------------
  - aap2_template_name: "[RHEL AAP Upgrade] Run LEAPP Upgrade"
    aap2_template_playbook: playbooks/leapp-upgrade.yml
    aap2_template_credentials:
      - RHEL AAP Upgrade - Linux Credentials
    aap2_template_inventory: RHEL AAP Upgrade - SCM Inventory
    aap2_template_project: RHEL AAP Upgrade
    # ------------------------------------
  - aap2_template_name: "[RHEL AAP Upgrade] Rollback system upgrade"
    aap2_template_playbook: playbooks/leapp-rollback.yml
    aap2_template_credentials:
      - RHEL AAP Upgrade - Linux Credentials
    aap2_template_inventory: RHEL AAP Upgrade - SCM Inventory
    aap2_template_project: RHEL AAP Upgrade
    # ------------------------------------
  - aap2_template_name: "[RHEL AAP Upgrade] Remove LVM Snapshots"
    aap2_template_playbook: playbooks/leapp-remove-snapshot.yml
    aap2_template_credentials:
      - RHEL AAP Upgrade - Linux Credentials
    aap2_template_inventory: RHEL AAP Upgrade - SCM Inventory
    aap2_template_project: RHEL AAP Upgrade
    # ------------------------------------
  - aap2_template_name: "[RHEL AAP Upgrade] Remediate inhibitors"
    aap2_template_playbook: playbooks/leapp-remediate.yml
    aap2_template_credentials:
      - RHEL AAP Upgrade - Linux Credentials
    aap2_template_inventory: RHEL AAP Upgrade - SCM Inventory
    aap2_template_project: RHEL AAP Upgrade

aap2_workflows:
  - aap2_workflow_name: "[RHEL AAP Upgrade] Prepare systems for upgrade"
    aap2_workflow_project: RHEL AAP Upgrade
    aap2_workflow_survey_enabled: true
    aap2_workflow_survey_spec:
      description: "RHEL Upgrade survey"
      name: "RHEL Upgrade survey"
      spec:
        - question_name: "Server name/Group Name"
          question_description: "Name of the server or server group as present in inventory"
          required: true
          type: "text"
          default: "rhel_servers"
          index: 0
          variable: "target_hosts"
    aap2_workflow_nodes:
      - node_name: leapp-pre-flight
        approval: false
        nodes_on_success:
          - leapp-configure-lvm-snapshot
        node_job_template: "[RHEL AAP Upgrade] Run pre-flight checks"
      - node_name: leapp-configure-lvm-snapshot
        approval: false
        nodes_on_success:
          - leapp-analysis
        node_job_template: "[RHEL AAP Upgrade] Configure LVM Snapshots for servers"
      - node_name: leapp-analysis
        approval: false
        node_job_template: "[RHEL AAP Upgrade] Run LEAPP Analysis"

  - aap2_workflow_name: "[RHEL AAP Upgrade] Remediate inhibitors and re-run analysis"
    aap2_workflow_project: RHEL AAP Upgrade
    aap2_workflow_survey_enabled: true
    aap2_workflow_survey_spec:
      description: "RHEL Upgrade survey"
      name: "RHEL Upgrade survey"
      spec:
        - question_name: "Server name/Group Name"
          question_description: "Name of the server or server group as present in inventory"
          required: true
          type: "text"
          default: "rhel_servers"
          index: 0
          variable: "target_hosts"
    aap2_workflow_nodes:
      - node_name: leapp-remediate-inhibitors
        approval: false
        nodes_on_success:
          - leapp-analysis
        node_job_template: "[RHEL AAP Upgrade] Remediate inhibitors"
      - node_name: leapp-analysis
        approval: false
        node_job_template: "[RHEL AAP Upgrade] Run LEAPP Analysis"

  - aap2_workflow_name: "[RHEL AAP Upgrade] Perform rollback on systems"
    aap2_workflow_project: RHEL AAP Upgrade
    aap2_workflow_survey_enabled: true
    aap2_workflow_survey_spec:
      description: "RHEL Upgrade survey"
      name: "RHEL Upgrade survey"
      spec:
        - question_name: "Server name/Group Name"
          question_description: "Name of the server or server group as present in inventory"
          required: true
          type: "text"
          default: "rhel_servers"
          index: 0
          variable: "target_hosts"
    aap2_workflow_nodes:
      - node_name: leapp-rollback
        approval: false
        nodes_on_success:
          - leapp-remove-lvm-snapshot
        node_job_template: "[RHEL AAP Upgrade] Rollback system upgrade"
      - node_name: leapp-remove-lvm-snapshot
        approval: false
        node_job_template: "[RHEL AAP Upgrade] Remove LVM Snapshots"
