---
version: 3
build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'
images:
  base_image:
    name: "registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest"
dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner

  python_interpreter:
    package_system: "python3.9"
    python_path: "/usr/bin/python3"

options:
  package_manager_path: /usr/bin/microdnf
