---
version: 3
build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'
images:
  base_image:
    name: "registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest"
dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner

  python_interpreter:
    package_system: "python3.9"
    python_path: "/usr/bin/python3"

options:
  package_manager_path: /usr/bin/microdnf
additional_build_steps:
  append_final:
  - RUN microdnf install -y glibc-langpack-en; sed -i 's/^LANG=.*/LANG="en_US.utf8"/' /etc/locale.conf; sed -i 's/^LC_ALL=.*/LC_ALL="en_US.utf8"/' /etc/locale.conf
  - ENV LANG=en_US.utf8
  - ENV LC_CTYPE=en_US.utf8
  - ENV LC_ALL=en_US.utf8
