---
- name: RHEL AAP Upgrade | Remediate common issues
  hosts: "{{ target_hosts | default('rhel_servers', true) }}"
  become: true
  roles:
    - role: infra.leapp.remediate
      vars:
      remediation_todo:
        - leapp_loaded_removed_kernel_drivers
