---
- name: RHEL AAP Upgrade | Remove snapshots
  hosts: "{{ target_hosts | default('rhel_servers', true) }}"
  become: true
  roles:
    - role: infra.lvm_snapshots.snapshot_remove
      snapshot_remove_set_name: ripu
